build: false

environment:
  matrix:
    - MINICONDA: "C:\\Miniconda-x64"
      PYTHON: 2.7
    - MINICONDA: "C:\\Miniconda36-x64"
      PYTHON: 3.6

install:
  - set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=%PYTHON% pip
  - activate test-environment
  - conda install -c conda-forge opencv
  - conda install pyqt
  - if %PYTHON% == 2.7 conda install scikit-image
  - pip install -r test_requirements.txt
  - pip install .

test_script:
  - pytest